# anishkny/sayhello orb definition
#
# To publish mutable dev version, execute:
#   circleci orb publish sayhello.orb.yml anishkny/sayhello@dev:first
#
# To publish immutable released version, execute:
#   circleci orb publish promote anishkny/sayhello@dev:first patch
#
# See usage in .circleci/config.yml

version: 2.1

jobs:
  sayhello:
    parameters:
      to:
        type: string
        default: "Hello World"
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo << parameters.to >>
      - run: ls -lhta
