version: 2.1

description: This is an inline job

orbs:
  hello: circleci/hello-build@0
  sayhello: anishkny/sayhello@0
  anchore: anchore/anchore-engine@1
  inline_example:
    jobs:
      my_inline_job:
        parameters:
          greeting_name:
            description: # a helpful description
            type: string
            default: olleh
        executor: my_inline_executor
        steps:
          - checkout
          - my_inline_command:
              greeting_name: <<parameters.greeting_name>>
    commands:
      my_inline_command:
        parameters:
          greeting_name:
            type: string
        steps:
          - run: |
              echo "hello <<parameters.greeting_name>>, from the inline command"
              find .
              ls -lhta
    executors:
      my_inline_executor:
        parameters:
          version:
            type: string
            default: "2.4"
        docker:
          - image: circleci/ruby:<<parameters.version>>

workflows:
  build-test-deploy:
    jobs:
      - sayhello/sayhello:
          name: my_orb
          to: अनीश
      - inline_example/my_inline_job:
          name: inline_orb
          greeting_name: world
      - hello/hello-build:
          name: circleci_orb
      - anchore/image_scan:
          name: anchore_orb
          image_name: alpine
