# anishkny/sayhello orb definition
# To deploy, execute: circleci orb publish sayhello.orb.yml anishkny/sayhello@dev:first
# See usage in ../.circleci/config.yml

version: 2.1

jobs:
  sayhello:
    parameters:
      to:
        type: string
        default: "Hello World"
    docker:
      - image: alpine
    steps:
      - run: echo << parameters.to >>
